// D&D 5e English → Spanish mechanical glossary
// IMPORTANT: longer/more-specific phrases MUST come before shorter ones
// to prevent partial matches corrupting longer phrases.

const REPLACEMENTS = [
  // ── "the + noun" patterns (gender-correct articles) ─────────────────────
  [/\bthe spell slot\b/gi, 'el espacio de conjuro'],
  [/\bthe spell slots\b/gi, 'los espacios de conjuro'],
  [/\bthe spell\b/gi, 'el conjuro'],
  [/\bthe spells\b/gi, 'los conjuros'],
  [/\bthe creature\b/gi, 'la criatura'],
  [/\bthe creatures\b/gi, 'las criaturas'],
  [/\bthe target\b/gi, 'el objetivo'],
  [/\bthe targets\b/gi, 'los objetivos'],
  [/\bthe attack\b/gi, 'el ataque'],
  [/\bthe attacks\b/gi, 'los ataques'],
  [/\bthe damage\b/gi, 'el daño'],
  [/\bthe effect\b/gi, 'el efecto'],
  [/\bthe effects\b/gi, 'los efectos'],
  [/\bthe area\b/gi, 'el área'],
  [/\bthe duration\b/gi, 'la duración'],
  [/\bthe turn\b/gi, 'el turno'],
  [/\bthe turns\b/gi, 'los turnos'],
  [/\bthe round\b/gi, 'la ronda'],
  [/\bthe rounds\b/gi, 'las rondas'],
  [/\bthe roll\b/gi, 'la tirada'],
  [/\bthe rolls\b/gi, 'las tiradas'],
  [/\bthe action\b/gi, 'la acción'],
  [/\bthe bonus action\b/gi, 'la acción adicional'],
  [/\bthe reaction\b/gi, 'la reacción'],
  [/\bthe ability\b/gi, 'la habilidad'],
  [/\bthe level\b/gi, 'el nivel'],
  [/\bthe die\b/gi, 'el dado'],
  [/\bthe dice\b/gi, 'los dados'],
  [/\bthe modifier\b/gi, 'el modificador'],
  [/\bthe weapon\b/gi, 'el arma'],
  [/\bthe weapons\b/gi, 'las armas'],
  [/\bthe armor\b/gi, 'la armadura'],
  [/\bthe shield\b/gi, 'el escudo'],
  [/\bthe class\b/gi, 'la clase'],
  [/\bthe subclass\b/gi, 'la subclase'],
  [/\bthe character\b/gi, 'el personaje'],
  [/\bthe saving throw\b/gi, 'la tirada de salvación'],
  [/\bthe saving throws\b/gi, 'las tiradas de salvación'],
  [/\bthe same\b/gi, 'el mismo'],
  [/\bthe following\b/gi, 'lo siguiente'],
  [/\bthe end\b/gi, 'el final'],
  [/\bthe start\b/gi, 'el inicio'],
  [/\bthe beginning\b/gi, 'el inicio'],
  [/\bthe total\b/gi, 'el total'],
  [/\bthe number\b/gi, 'el número'],
  [/\bthe amount\b/gi, 'la cantidad'],
  [/\bthe bonus\b/gi, 'el bonificador'],
  [/\bthe penalty\b/gi, 'la penalización'],
  [/\bthe proficiency bonus\b/gi, 'el bonificador de competencia'],
  [/\bthe initiative\b/gi, 'la iniciativa'],
  [/\bthe movement\b/gi, 'el movimiento'],
  [/\bthe speed\b/gi, 'la velocidad'],
  [/\bthe range\b/gi, 'el alcance'],
  [/\bthe ground\b/gi, 'el suelo'],
  [/\bthe floor\b/gi, 'el suelo'],
  [/\bthe surface\b/gi, 'la superficie'],
  [/\bthe wall\b/gi, 'la pared'],
  [/\bthe ceiling\b/gi, 'el techo'],
  [/\bthe door\b/gi, 'la puerta'],
  [/\bthe next\b/gi, 'el siguiente'],
  [/\bthe current\b/gi, 'el actual'],
  [/\bthe pool\b/gi, 'la reserva'],
  [/\bthe cost\b/gi, 'el coste'],
  [/\bthe slot\b/gi, 'el espacio'],
  [/\bthe feat\b/gi, 'la dote'],
  [/\bthe feats\b/gi, 'las dotes'],
  [/\bthe feature\b/gi, 'el rasgo'],
  [/\bthe features\b/gi, 'los rasgos'],
  [/\bthe trait\b/gi, 'el rasgo'],
  [/\bthe traits\b/gi, 'los rasgos'],
  [/\bthe task\b/gi, 'la tarea'],
  [/\bthe command\b/gi, 'la orden'],
  [/\bthe commands\b/gi, 'las órdenes'],
  [/\bthe order\b/gi, 'la orden'],
  [/\bthe orders\b/gi, 'las órdenes'],
  [/\bthe condition\b/gi, 'la condición'],
  [/\bthe conditions\b/gi, 'las condiciones'],
  [/\bthe trigger\b/gi, 'el desencadenante'],
  [/\bthe source\b/gi, 'la fuente'],
  [/\bthe distance\b/gi, 'la distancia'],
  [/\bthe time\b/gi, 'el tiempo'],
  [/\bthe period\b/gi, 'el período'],
  [/\bthe control\b/gi, 'el control'],
  [/\bthe space\b/gi, 'el espacio'],
  [/\bthe weight\b/gi, 'el peso'],
  [/\bthe point\b/gi, 'el punto'],
  [/\bthe points\b/gi, 'los puntos'],
  [/\bthe range\b/gi, 'el alcance'],
  [/\bthe skeleton\b/gi, 'el esqueleto'],
  [/\bthe zombie\b/gi, 'el zombi'],
  [/\bthe corpse\b/gi, 'el cadáver'],
  [/\bthe bones\b/gi, 'los huesos'],
  [/\bthe pile\b/gi, 'el montón'],
  [/\bthe chamber\b/gi, 'la cámara'],
  [/\bthe corridor\b/gi, 'el corredor'],
  [/\bthe chest\b/gi, 'el cofre'],
  [/\bthe bag\b/gi, 'la bolsa'],
  [/\bthe object\b/gi, 'el objeto'],
  [/\bthe objects\b/gi, 'los objetos'],
  [/\bthe item\b/gi, 'el objeto'],
  [/\bthe items\b/gi, 'los objetos'],
  [/\bthe terrain\b/gi, 'el terreno'],
  [/\bthe location\b/gi, 'la ubicación'],
  [/\bthe position\b/gi, 'la posición'],
  [/\bthe path\b/gi, 'el camino'],
  [/\bthe way\b/gi, 'el camino'],
  [/\bthe body\b/gi, 'el cuerpo'],
  [/\bthe bodies\b/gi, 'los cuerpos'],
  [/\bthe spirit\b/gi, 'el espíritu'],
  [/\bthe soul\b/gi, 'el alma'],
  [/\bthe mind\b/gi, 'la mente'],
  [/\bthe heart\b/gi, 'el corazón'],
  [/\bthe eye\b/gi, 'el ojo'],
  [/\bthe eyes\b/gi, 'los ojos'],
  [/\bthe hand\b/gi, 'la mano'],
  [/\bthe hands\b/gi, 'las manos'],
  [/\bthe arm\b/gi, 'el brazo'],
  [/\bthe arms\b/gi, 'los brazos'],
  [/\bthe leg\b/gi, 'la pierna'],
  [/\bthe legs\b/gi, 'las piernas'],
  [/\bthe head\b/gi, 'la cabeza'],
  [/\bthe body\b/gi, 'el cuerpo'],
  [/\bthe blood\b/gi, 'la sangre'],
  [/\bthe flesh\b/gi, 'la carne'],
  [/\bthe bone\b/gi, 'el hueso'],
  [/\bthe bones\b/gi, 'los huesos'],
  [/\bthe skin\b/gi, 'la piel'],
  [/\bthe dust\b/gi, 'el polvo'],
  [/\bthe ash\b/gi, 'la ceniza'],
  [/\bthe ashes\b/gi, 'las cenizas'],
  [/\bthe smoke\b/gi, 'el humo'],
  [/\bthe fire\b/gi, 'el fuego'],
  [/\bthe flame\b/gi, 'la llama'],
  [/\bthe flames\b/gi, 'las llamas'],
  [/\bthe light\b/gi, 'la luz'],
  [/\bthe darkness\b/gi, 'la oscuridad'],
  [/\bthe shadow\b/gi, 'la sombra'],
  [/\bthe shadows\b/gi, 'las sombras'],
  [/\bthe ground\b/gi, 'el suelo'],
  [/\bthe sky\b/gi, 'el cielo'],
  [/\bthe sun\b/gi, 'el sol'],
  [/\bthe moon\b/gi, 'la luna'],
  [/\bthe star\b/gi, 'la estrella'],
  [/\bthe stars\b/gi, 'las estrellas'],
  [/\bthe wind\b/gi, 'el viento'],
  [/\bthe storm\b/gi, 'la tormenta'],
  [/\bthe water\b/gi, 'el agua'],
  [/\bthe earth\b/gi, 'la tierra'],
  [/\bthe air\b/gi, 'el aire'],
  [/\bthe void\b/gi, 'el vacío'],
  [/\bthe plane\b/gi, 'el plano'],
  [/\bthe planes\b/gi, 'los planos'],
  [/\bthe realm\b/gi, 'el reino'],
  [/\bthe world\b/gi, 'el mundo'],

  // ── "a/an + noun" patterns ────────────────────────────────────────────────
  [/\ba spell slot\b/gi, 'un espacio de conjuro'],
  [/\ba higher-level spell slot\b/gi, 'un espacio de conjuro de nivel superior'],
  [/\ba spell\b/gi, 'un conjuro'],
  [/\ba creature\b/gi, 'una criatura'],
  [/\ban creature\b/gi, 'una criatura'],
  [/\ba target\b/gi, 'un objetivo'],
  [/\ba weapon\b/gi, 'un arma'],
  [/\ba saving throw\b/gi, 'una tirada de salvación'],
  [/\ba bonus action\b/gi, 'una acción adicional'],
  [/\ban action\b/gi, 'una acción'],
  [/\ba reaction\b/gi, 'una reacción'],
  [/\ba roll\b/gi, 'una tirada'],
  [/\ba turn\b/gi, 'un turno'],
  [/\ba round\b/gi, 'una ronda'],
  [/\ba die\b/gi, 'un dado'],
  [/\ba level\b/gi, 'un nivel'],
  [/\ba minute\b/gi, 'un minuto'],
  [/\ban hour\b/gi, 'una hora'],
  [/\ba day\b/gi, 'un día'],
  [/\ba week\b/gi, 'una semana'],
  [/\ba year\b/gi, 'un año'],
  [/\ba command\b/gi, 'una orden'],
  [/\ba general command\b/gi, 'una orden general'],
  [/\ba pile\b/gi, 'un montón'],
  [/\ba corpse\b/gi, 'un cadáver'],
  [/\ba skeleton\b/gi, 'un esqueleto'],
  [/\ba zombie\b/gi, 'un zombi'],
  [/\ba chamber\b/gi, 'una cámara'],
  [/\ba corridor\b/gi, 'un corredor'],
  [/\ba creature\b/gi, 'una criatura'],
  [/\ba number of\b/gi, 'una cantidad de'],
  [/\ba bonus\b/gi, 'un bonificador'],
  [/\ba penalty\b/gi, 'una penalización'],
  [/\ba pool\b/gi, 'una reserva'],
  [/\ban effect\b/gi, 'un efecto'],
  [/\ba location\b/gi, 'una ubicación'],
  [/\ba task\b/gi, 'una tarea'],
  [/\ba charge\b/gi, 'una carga'],
  [/\ba condition\b/gi, 'una condición'],
  [/\ba point\b/gi, 'un punto'],
  [/\ba new\b/gi, 'una nueva'],

  // ── Phrases first (order matters) ──────────────────────────────────────

  // Spell slot phrases
  [/\busing a higher-level spell slot\b/gi, 'usando un espacio de conjuro de nivel superior'],
  [/\busing a higher level spell slot\b/gi, 'usando un espacio de conjuro de nivel superior'],
  [/\bspell slot level\b/gi, 'nivel del espacio de conjuro'],
  [/\bspell slot\b/gi, 'espacio de conjuro'],
  [/\bspell slots\b/gi, 'espacios de conjuro'],

  // Hit points (must come before bare "hit" or "points")
  [/\btemporary hit points?\b/gi, 'puntos de golpe temporales'],
  [/\bhit point maximum\b/gi, 'máximo de puntos de golpe'],
  [/\bhit point dice\b/gi, 'dados de golpe'],
  [/\bhit point die\b/gi, 'dado de golpe'],
  [/\bhit points?\b/gi, 'puntos de golpe'],
  [/\bhit dice\b/gi, 'dados de golpe'],
  [/\bhit die\b/gi, 'dado de golpe'],

  // Attack phrases
  [/\bmelee weapon attack\b/gi, 'ataque de arma cuerpo a cuerpo'],
  [/\branged weapon attack\b/gi, 'ataque de arma a distancia'],
  [/\bmelee spell attack\b/gi, 'ataque de conjuro cuerpo a cuerpo'],
  [/\branged spell attack\b/gi, 'ataque de conjuro a distancia'],
  [/\bmelee attack\b/gi, 'ataque cuerpo a cuerpo'],
  [/\branged attack\b/gi, 'ataque a distancia'],
  [/\battack roll\b/gi, 'tirada de ataque'],
  [/\battack rolls\b/gi, 'tiradas de ataque'],
  [/\bcritical hit\b/gi, 'golpe crítico'],
  [/\bopportunity attack\b/gi, 'ataque de oportunidad'],
  [/\bsneak attack\b/gi, 'ataque furtivo'],
  [/\bunarmed strike\b/gi, 'golpe sin arma'],
  [/\battack\b/gi, 'ataque'],
  [/\battacks\b/gi, 'ataques'],

  // Saving throws
  [/\bdeath saving throw\b/gi, 'tirada de salvación contra la muerte'],
  [/\bsaving throw\b/gi, 'tirada de salvación'],
  [/\bsaving throws\b/gi, 'tiradas de salvación'],
  [/\bspell save DC\b/gi, 'CD de salvación del conjuro'],
  [/\bfailed save\b/gi, 'salvación fallida'],
  [/\bsuccessful save\b/gi, 'salvación exitosa'],

  // Ability score phrases
  [/\bspellcasting ability modifier\b/gi, 'modificador de característica de lanzamiento'],
  [/\bspellcasting ability\b/gi, 'característica de lanzamiento'],
  [/\bability check\b/gi, 'prueba de característica'],
  [/\bability score improvement\b/gi, 'mejora de puntuación de característica'],
  [/\bability score\b/gi, 'puntuación de característica'],
  [/\bability modifier\b/gi, 'modificador de característica'],
  [/\bability scores\b/gi, 'puntuaciones de característica'],
  [/\bability checks\b/gi, 'pruebas de característica'],

  // Damage phrases
  [/\bdamage roll\b/gi, 'tirada de daño'],
  [/\bdamage rolls\b/gi, 'tiradas de daño'],
  [/\bdamage type\b/gi, 'tipo de daño'],
  [/\bdamage types\b/gi, 'tipos de daño'],
  [/\bhalf as much damage\b/gi, 'la mitad del daño'],
  [/\bhalf damage\b/gi, 'la mitad del daño'],
  [/\bno damage\b/gi, 'ningún daño'],
  [/\bextra damage\b/gi, 'daño adicional'],

  // Damage types (with "damage" suffix)
  [/\bacid damage\b/gi, 'daño de ácido'],
  [/\bbludgeoning damage\b/gi, 'daño contundente'],
  [/\bcold damage\b/gi, 'daño de frío'],
  [/\bfire damage\b/gi, 'daño de fuego'],
  [/\bforce damage\b/gi, 'daño de fuerza'],
  [/\blightning damage\b/gi, 'daño de relámpago'],
  [/\bnecrotic damage\b/gi, 'daño necrótico'],
  [/\bpiercing damage\b/gi, 'daño perforante'],
  [/\bpoison damage\b/gi, 'daño de veneno'],
  [/\bpsychic damage\b/gi, 'daño psíquico'],
  [/\bradiant damage\b/gi, 'daño radiante'],
  [/\bslashing damage\b/gi, 'daño cortante'],
  [/\bthunder damage\b/gi, 'daño de trueno'],

  // Verb+target phrases (target is both noun and verb — must handle verb form first)
  [/\bcan target\b/gi, 'puedes elegir como objetivo'],
  [/\bto target\b/gi, 'como objetivo'],
  [/\byou target\b/gi, 'eliges como objetivo'],
  [/\bmust target\b/gi, 'debe elegir como objetivo'],
  [/\btargets? (one|two|three|four|five|six|seven|eight) creatures?\b/gi, 'elige como objetivo $1 criaturas'],

  // Número + criatura (debe ir antes de traducciones de números individuales)
  [/\bup to (\d+)\b/gi, 'hasta $1'],
  [/\bone additional creature\b/gi, 'una criatura adicional'],
  [/\btwo additional creatures\b/gi, 'dos criaturas adicionales'],
  [/\bthree additional creatures\b/gi, 'tres criaturas adicionales'],
  [/\bone more creature\b/gi, 'una criatura más'],

  // "must" + verb phrases
  [/\bmust succeed\b/gi, 'debe tener éxito'],
  [/\bmust make\b/gi, 'debe hacer'],
  [/\bmust take\b/gi, 'debe recibir'],
  [/\bmust spend\b/gi, 'debe gastar'],
  [/\bmust use\b/gi, 'debe usar'],
  [/\bmust be\b/gi, 'debe ser'],
  [/\bmust have\b/gi, 'debe tener'],
  [/\bmust subtract\b/gi, 'debe restar'],
  [/\bmust roll\b/gi, 'debe tirar'],
  [/\bmust\b/gi, 'debe'],

  // "each" + verb (plural subject)
  [/\beach must make\b/gi, 'cada una debe hacer'],
  [/\beach make\b/gi, 'cada una hace'],

  // Temporal/conditional phrases
  [/\bwhenever\b/gi, 'siempre que'],
  [/\bwherever\b/gi, 'dondequiera que'],
  [/\bwhoever\b/gi, 'quien'],
  [/\bwhatever\b/gi, 'lo que sea'],
  [/\bwhenever\b/gi, 'siempre que'],

  // "make a/an" phrases
  [/\bmakes? an? attack roll\b/gi, 'realiza una tirada de ataque'],
  [/\bmakes? an? saving throw\b/gi, 'realiza una tirada de salvación'],
  [/\bmakes? an? ability check\b/gi, 'realiza una prueba de característica'],
  [/\bmake an? attack roll\b/gi, 'realiza una tirada de ataque'],
  [/\bmake an? saving throw\b/gi, 'realiza una tirada de salvación'],
  [/\bmakes?\b/gi, 'realiza'],
  [/\bmade\b/gi, 'realizado'],
  [/\bmake\b/gi, 'realizar'],
  [/\bmaking\b/gi, 'realizando'],

  // Missing verbs
  [/\bsubtract\b/gi, 'restar'],
  [/\bsubtracts\b/gi, 'resta'],
  [/\bsubtracted\b/gi, 'restado'],
  [/\badd\b/gi, 'añadir'],
  [/\badds\b/gi, 'añade'],
  [/\badded\b/gi, 'añadido'],
  [/\bapply\b/gi, 'aplicar'],
  [/\bapplies\b/gi, 'aplica'],
  [/\bapplied\b/gi, 'aplicado'],
  [/\bextend\b/gi, 'extender'],
  [/\bextends\b/gi, 'extiende'],
  [/\bextended\b/gi, 'extendido'],
  [/\bchoose\b/gi, 'elegir'],
  [/\bchooses\b/gi, 'elige'],
  [/\bchose\b/gi, 'eligió'],
  [/\bchoosing\b/gi, 'eligiendo'],
  [/\bdecide\b/gi, 'decidir'],
  [/\bdecides\b/gi, 'decide'],
  [/\bdecided\b/gi, 'decidido'],
  [/\bhave\b/gi, 'tener'],
  [/\bhas\b/gi, 'tiene'],
  [/\bhad\b/gi, 'tenía'],
  [/\bhaving\b/gi, 'teniendo'],
  [/\bwill\b/gi, 'va a'],
  [/\bcan\b/gi, 'puede'],
  [/\bcould\b/gi, 'podría'],
  [/\bshould\b/gi, 'debería'],
  [/\bwould\b/gi, 'va a'],
  [/\bmight\b/gi, 'podría'],
  [/\bmay\b/gi, 'puede'],

  // Common D&D verb phrases
  [/\broll a d(\d+)\b/gi, 'tira un d$1'],
  [/\broll (\d+)d(\d+)\b/gi, 'tira $1d$2'],
  [/\broll the dice\b/gi, 'tira los dados'],
  [/\broll for\b/gi, 'tira para'],
  [/\broll on\b/gi, 'tira en'],
  [/\blay on hands\b/gi, 'imposición de manos'],
  [/\bchannel divinity\b/gi, 'canalizar divinidad'],
  [/\bturn undead\b/gi, 'ahuyentar no muertos'],
  [/\bwild shape\b/gi, 'forma salvaje'],
  [/\bsecond wind\b/gi, 'segundo aliento'],
  [/\baction surge\b/gi, 'oleada de acción'],
  [/\bfighting style\b/gi, 'estilo de combate'],
  [/\bextra attack\b/gi, 'ataque adicional'],
  [/\bcunning action\b/gi, 'acción astuta'],
  [/\buncanny dodge\b/gi, 'esquiva prodigiosa'],
  [/\barcane recovery\b/gi, 'recuperación arcana'],
  [/\bdivine smite\b/gi, 'castigo divino'],
  [/\bdivine sense\b/gi, 'sentido divino'],
  [/\bflurry of blows\b/gi, 'lluvia de golpes'],
  [/\bstunning strike\b/gi, 'golpe aturdidor'],

  // Area / range phrases
  [/\barea of effect\b/gi, 'área de efecto'],
  [/\bline of sight\b/gi, 'línea de visión'],
  [/\bwithin range\b/gi, 'dentro del alcance'],
  [/\bout of range\b/gi, 'fuera del alcance'],
  [/\bat range\b/gi, 'a distancia'],
  [/\bwithin (\d+) feet\b/gi, 'a $1 pies'],
  [/\b(\d+)-foot\b/gi, 'de $1 pies'],
  [/\bflying speed\b/gi, 'velocidad de vuelo'],
  [/\bswimming speed\b/gi, 'velocidad de natación'],
  [/\bclimbing speed\b/gi, 'velocidad de escalar'],
  [/\bwalking speed\b/gi, 'velocidad caminando'],

  // Rest phrases
  [/\bshort rest\b/gi, 'descanso corto'],
  [/\blong rest\b/gi, 'descanso largo'],
  [/\bshort rests\b/gi, 'descansos cortos'],
  [/\blong rests\b/gi, 'descansos largos'],
  [/\bfinish a short rest\b/gi, 'terminar un descanso corto'],
  [/\bfinish a long rest\b/gi, 'terminar un descanso largo'],

  // Common phrases
  [/\bat the start of\b/gi, 'al inicio de'],
  [/\bat the end of\b/gi, 'al final de'],
  [/\buntil the start of\b/gi, 'hasta el inicio de'],
  [/\buntil the end of\b/gi, 'hasta el final de'],
  [/\bonce per\b/gi, 'una vez por'],
  [/\bat higher levels\b/gi, 'en niveles superiores'],
  [/\busing a higher[- ]level\b/gi, 'usando un nivel superior'],
  [/\bequal to\b/gi, 'igual a'],
  [/\bup to\b/gi, 'hasta'],
  [/\bat will\b/gi, 'a voluntad'],
  [/\bon a failed save\b/gi, 'en una salvación fallida'],
  [/\bon a successful save\b/gi, 'en una salvación exitosa'],
  [/\bwhen you cast this spell\b/gi, 'cuando lanzas este conjuro'],
  [/\bwhen you cast\b/gi, 'cuando lanzas'],
  [/\bwhen you take\b/gi, 'cuando recibes'],
  [/\bwhen you make\b/gi, 'cuando realizas'],
  [/\bwhen you use\b/gi, 'cuando usas'],
  [/\bif you fail\b/gi, 'si fallas'],
  [/\bif you succeed\b/gi, 'si tienes éxito'],
  [/\bas a bonus action\b/gi, 'como acción adicional'],
  [/\bas an action\b/gi, 'como acción'],
  [/\bas a reaction\b/gi, 'como reacción'],
  [/\bfor the duration\b/gi, 'durante la duración'],
  [/\bfor (\d+) (minute|hour|round|day)s?\b/gi, 'durante $1 $2'],
  [/\bno longer\b/gi, 'ya no'],
  [/\bone or more\b/gi, 'uno o más'],
  [/\bone of the following\b/gi, 'una de las siguientes'],
  [/\bone of your choice\b/gi, 'una de tu elección'],
  [/\bof your choice\b/gi, 'de tu elección'],
  [/\byou choose\b/gi, 'eliges'],
  [/\byou chose\b/gi, 'elegiste'],
  [/\bthat you can see\b/gi, 'que puedes ver'],
  [/\byou can see\b/gi, 'puedes ver'],
  [/\byou can\b/gi, 'puedes'],
  [/\byou cannot\b/gi, 'no puedes'],
  [/\byou may\b/gi, 'puedes'],
  [/\byou must\b/gi, 'debes'],
  [/\byou have\b/gi, 'tienes'],
  [/\byou had\b/gi, 'tenías'],
  [/\byou are\b/gi, 'estás'],
  [/\byou were\b/gi, 'estabas'],
  [/\byou gain\b/gi, 'ganas'],
  [/\byou take\b/gi, 'recibes'],
  [/\byou deal\b/gi, 'infliges'],
  [/\byou make\b/gi, 'realizas'],
  [/\byou roll\b/gi, 'tiras'],
  [/\byou lose\b/gi, 'pierdes'],
  [/\byou spend\b/gi, 'gastas'],
  [/\byou use\b/gi, 'usas'],
  [/\byou regain\b/gi, 'recuperas'],
  [/\byou restore\b/gi, 'restauras'],
  [/\byou become\b/gi, 'te conviertes en'],
  [/\byou tap\b/gi, 'accedes'],
  [/\binto your\b/gi, 'a tu'],
  [/\blife force\b/gi, 'fuerza vital'],
  [/\bnumber of\b/gi, 'número de'],
  [/\ba number\b/gi, 'una cantidad'],
  [/\bsuch as\b/gi, 'como por ejemplo'],
  [/\bmore than\b/gi, 'más de'],
  [/\bless than\b/gi, 'menos de'],
  [/\bother than\b/gi, 'distinto a'],
  [/\brather than\b/gi, 'en lugar de'],
  [/\bin addition\b/gi, 'además'],
  [/\bin addition to\b/gi, 'además de'],
  [/\bas well as\b/gi, 'así como'],
  [/\bat least\b/gi, 'al menos'],
  [/\bno more than\b/gi, 'no más de'],
  [/\bin place of\b/gi, 'en lugar de'],
  [/\binstead of\b/gi, 'en lugar de'],
  [/\bregardless of\b/gi, 'independientemente de'],
  [/\bthe number of\b/gi, 'el número de'],
  [/\bthe total\b/gi, 'el total'],
  [/\ball creatures\b/gi, 'todas las criaturas'],
  [/\beach creature\b/gi, 'cada criatura'],
  [/\beach other\b/gi, 'entre sí'],
  [/\ball other\b/gi, 'todos los demás'],
  [/\bone creature\b/gi, 'una criatura'],

  // Proficiency
  [/\bproficiency bonus\b/gi, 'bonificador de competencia'],
  [/\bproficiency bonuses\b/gi, 'bonificadores de competencia'],
  [/\bproficient in\b/gi, 'competente en'],
  [/\bproficient with\b/gi, 'competente con'],
  [/\bproficiency with\b/gi, 'competencia con'],
  [/\bproficiency in\b/gi, 'competencia en'],
  [/\bdouble your proficiency\b/gi, 'el doble de tu bonificador de competencia'],

  // Advantage / disadvantage
  [/\badvantage on\b/gi, 'ventaja en'],
  [/\bdisadvantage on\b/gi, 'desventaja en'],
  [/\bhas advantage\b/gi, 'tiene ventaja'],
  [/\bhas disadvantage\b/gi, 'tiene desventaja'],
  [/\bwith advantage\b/gi, 'con ventaja'],
  [/\bwith disadvantage\b/gi, 'con desventaja'],
  [/\badvantage\b/gi, 'ventaja'],
  [/\bdisadvantage\b/gi, 'desventaja'],

  // ── Individual terms ────────────────────────────────────────────────────

  // Ability scores
  [/\bstrength\b/gi, 'fuerza'],
  [/\bdexterity\b/gi, 'destreza'],
  [/\bconstitution\b/gi, 'constitución'],
  [/\bintelligence\b/gi, 'inteligencia'],
  [/\bwisdom\b/gi, 'sabiduría'],
  [/\bcharisma\b/gi, 'carisma'],

  // Actions
  [/\bbonus action\b/gi, 'acción adicional'],
  [/\bbonus actions\b/gi, 'acciones adicionales'],
  [/\bfree action\b/gi, 'acción gratuita'],
  [/\baction\b/gi, 'acción'],
  [/\bactions\b/gi, 'acciones'],
  [/\breaction\b/gi, 'reacción'],
  [/\breactions\b/gi, 'reacciones'],
  [/\bmovement\b/gi, 'movimiento'],

  // Combat
  [/\barmor class\b/gi, 'clase de armadura'],
  [/\bdifficulty class\b/gi, 'clase de dificultad'],
  [/\bchallenge rating\b/gi, 'rango de desafío'],
  [/\binitiative\b/gi, 'iniciativa'],
  [/\bsave\b/g, 'salvación'],
  [/\bsaves\b/g, 'salvaciones'],

  // Conditions
  [/\bblinded\b/gi, 'cegado'],
  [/\bcharmed\b/gi, 'hechizado'],
  [/\bdeafened\b/gi, 'ensordecido'],
  [/\bexhaustion\b/gi, 'agotamiento'],
  [/\bfrightened\b/gi, 'asustado'],
  [/\bgrappled\b/gi, 'aferrado'],
  [/\bincapacitated\b/gi, 'incapacitado'],
  [/\binvisible\b/gi, 'invisible'],
  [/\bparalyzed\b/gi, 'paralizado'],
  [/\bpetrified\b/gi, 'petrificado'],
  [/\bpoisoned\b/gi, 'envenenado'],
  [/\bprone\b/gi, 'derribado'],
  [/\brestrained\b/gi, 'inmovilizado'],
  [/\bstunned\b/gi, 'aturdido'],
  [/\bunconscious\b/gi, 'inconsciente'],
  [/\bfrightened\b/gi, 'asustado'],

  // Damage types (standalone — after "X damage" phrases)
  [/\bbludgeoning\b/gi, 'contundente'],
  [/\bpiercing\b/gi, 'perforante'],
  [/\bslashing\b/gi, 'cortante'],
  [/\bnecrotic\b/gi, 'necrótico'],
  [/\bradiant\b/gi, 'radiante'],
  [/\bpsychic\b/gi, 'psíquico'],
  [/\bthunder\b/gi, 'trueno'],
  [/\blightning\b/gi, 'relámpago'],
  [/\bpoison\b/gi, 'veneno'],
  [/\bacid\b/gi, 'ácido'],
  [/\bcold\b/gi, 'frío'],
  [/\bfire\b/gi, 'fuego'],

  // Spellcasting
  [/\bcantrip\b/gi, 'truco'],
  [/\bcantrips\b/gi, 'trucos'],
  [/\bspellcaster\b/gi, 'lanzador de conjuros'],
  [/\bspellcasting focus\b/gi, 'foco de conjuración'],
  [/\barcane focus\b/gi, 'foco arcano'],
  [/\bdruidic focus\b/gi, 'foco druídico'],
  [/\bspell\b/gi, 'conjuro'],
  [/\bspells\b/gi, 'conjuros'],
  [/\bcast\b/gi, 'lanzar'],
  [/\bcasting\b/gi, 'lanzamiento'],
  [/\bcasting time\b/gi, 'tiempo de lanzamiento'],
  [/\bcomponents\b/gi, 'componentes'],
  [/\bduration\b/gi, 'duración'],
  [/\binstantaneous\b/gi, 'instantánea'],
  [/\bpermanent\b/gi, 'permanente'],
  [/\bconcentrate\b/gi, 'concentrarse'],
  [/\bconcentrating\b/gi, 'concentrándose'],
  [/\bconcentration\b/gi, 'concentración'],
  [/\bdispel\b/gi, 'disipar'],
  [/\bdismiss\b/gi, 'despedir'],
  [/\bsummon\b/gi, 'convocar'],
  [/\bsummoned\b/gi, 'convocado'],

  // Magic schools
  [/\bevocation\b/gi, 'evocación'],
  [/\babjuration\b/gi, 'abjuración'],
  [/\bconjuration\b/gi, 'conjuración'],
  [/\bdivination\b/gi, 'adivinación'],
  [/\benchantment\b/gi, 'encantamiento'],
  [/\billusion\b/gi, 'ilusión'],
  [/\bnecromancy\b/gi, 'nigromancia'],
  [/\btransmutation\b/gi, 'transmutación'],

  // Creature types
  [/\bhumanoid\b/gi, 'humanoide'],
  [/\bhumanoids\b/gi, 'humanoides'],
  [/\bundead\b/gi, 'no muerto'],
  [/\bmonster\b/gi, 'monstruo'],
  [/\bfiend\b/gi, 'infernal'],
  [/\bcelestial\b/gi, 'celestial'],
  [/\bfey\b/gi, 'feérico'],
  [/\bdragon\b/gi, 'dragón'],
  [/\bdragonborn\b/gi, 'dracónido'],
  [/\bdwarf\b/gi, 'enano'],
  [/\belf\b/gi, 'elfo'],
  [/\bhalf-elf\b/gi, 'semielfo'],
  [/\bhalf-orc\b/gi, 'semiorco'],
  [/\bhalfling\b/gi, 'mediano'],
  [/\bgnome\b/gi, 'gnomo'],
  [/\bhuman\b/gi, 'humano'],
  [/\btiefling\b/gi, 'tiefling'],
  [/\bbeast\b/gi, 'bestia'],
  [/\bcreature\b/gi, 'criatura'],
  [/\bcreatures\b/gi, 'criaturas'],
  [/\benemy\b/gi, 'enemigo'],
  [/\benemies\b/gi, 'enemigos'],
  [/\bally\b/gi, 'aliado'],
  [/\ballies\b/gi, 'aliados'],
  [/\btarget\b/gi, 'objetivo'],
  [/\btargets\b/gi, 'objetivos'],

  // Skills
  [/\bacrobatics\b/gi, 'acrobacias'],
  [/\banimal handling\b/gi, 'trato con animales'],
  [/\barcana\b/gi, 'arcanos'],
  [/\bathletics\b/gi, 'atletismo'],
  [/\bdeception\b/gi, 'engaño'],
  [/\bhistory\b/gi, 'historia'],
  [/\binsight\b/gi, 'perspicacia'],
  [/\bintimidation\b/gi, 'intimidación'],
  [/\binvestigation\b/gi, 'investigación'],
  [/\bmedicine\b/gi, 'medicina'],
  [/\bnature\b/gi, 'naturaleza'],
  [/\bperception\b/gi, 'percepción'],
  [/\bperformance\b/gi, 'actuación'],
  [/\bpersuasion\b/gi, 'persuasión'],
  [/\breligion\b/gi, 'religión'],
  [/\bsleight of hand\b/gi, 'juego de manos'],
  [/\bstealth\b/gi, 'sigilo'],
  [/\bsurvival\b/gi, 'supervivencia'],
  [/\bproficiency\b/gi, 'competencia'],
  [/\bproficient\b/gi, 'competente'],
  [/\bexpertise\b/gi, 'maestría'],

  // Senses
  [/\bpassive perception\b/gi, 'percepción pasiva'],
  [/\bdarkvision\b/gi, 'visión en la oscuridad'],
  [/\btremorsense\b/gi, 'sentido sísmico'],
  [/\bblindsight\b/gi, 'percepción ciega'],
  [/\btruesight\b/gi, 'visión verdadera'],

  // Equipment
  [/\blight armor\b/gi, 'armadura ligera'],
  [/\bmedium armor\b/gi, 'armadura media'],
  [/\bheavy armor\b/gi, 'armadura pesada'],
  [/\bsimple weapons\b/gi, 'armas simples'],
  [/\bmartial weapons\b/gi, 'armas marciales'],
  [/\bsimple weapon\b/gi, 'arma simple'],
  [/\bmartial weapon\b/gi, 'arma marcial'],
  [/\bmagic items\b/gi, 'objetos mágicos'],
  [/\bmagic item\b/gi, 'objeto mágico'],
  [/\battunement\b/gi, 'sintonía'],
  [/\battuned\b/gi, 'sintonizado'],
  [/\barmor\b/gi, 'armadura'],
  [/\bshield\b/gi, 'escudo'],
  [/\bweapons\b/gi, 'armas'],
  [/\bweapon\b/gi, 'arma'],

  // Common verbs
  [/\bregains\b/gi, 'recupera'],
  [/\bregain\b/gi, 'recuperar'],
  [/\bregained\b/gi, 'recuperado'],
  [/\brestores\b/gi, 'restaura'],
  [/\brestore\b/gi, 'restaurar'],
  [/\brestored\b/gi, 'restaurado'],
  [/\bheals\b/gi, 'cura'],
  [/\bheal\b/gi, 'curar'],
  [/\bhealed\b/gi, 'curado'],
  [/\bhealing\b/gi, 'curación'],
  [/\brolls?\b/gi, 'tirada'],
  [/\brolled\b/gi, 'obtenido'],
  [/\brolling\b/gi, 'tirando'],
  [/\broll\b/gi, 'tirar'],
  [/\bspends\b/gi, 'gasta'],
  [/\bspend\b/gi, 'gastar'],
  [/\bspent\b/gi, 'gastado'],
  [/\bexpends\b/gi, 'gasta'],
  [/\bexpend\b/gi, 'gastar'],
  [/\bexpended\b/gi, 'gastado'],
  [/\bunexpended\b/gi, 'sin gastar'],
  [/\bincreases\b/gi, 'aumenta'],
  [/\bincrease\b/gi, 'aumentar'],
  [/\bincreased\b/gi, 'aumentado'],
  [/\bdecreases\b/gi, 'disminuye'],
  [/\bdecrease\b/gi, 'disminuir'],
  [/\breduces\b/gi, 'reduce'],
  [/\breduce\b/gi, 'reducir'],
  [/\breduced\b/gi, 'reducido'],
  [/\bdeals\b/gi, 'inflige'],
  [/\bdeal\b/gi, 'infligir'],
  [/\bdealt\b/gi, 'infligido'],
  [/\btakes?\b/gi, 'recibe'],
  [/\btaken\b/gi, 'recibido'],
  [/\bgains?\b/gi, 'gana'],
  [/\bgained\b/gi, 'ganado'],
  [/\bloses?\b/gi, 'pierde'],
  [/\blost\b/gi, 'perdido'],
  [/\bsucceeds?\b/gi, 'tiene éxito'],
  [/\bsucceeded\b/gi, 'tuvo éxito'],
  [/\bfails?\b/gi, 'falla'],
  [/\bfailed\b/gi, 'falló'],
  [/\bbegins?\b/gi, 'comienza'],
  [/\bbegun\b/gi, 'comenzado'],
  [/\bends?\b/gi, 'termina'],
  [/\bended\b/gi, 'terminado'],
  [/\bappears?\b/gi, 'aparece'],
  [/\bdisappears?\b/gi, 'desaparece'],
  [/\bstabilize\b/gi, 'estabilizar'],
  [/\bstabilized\b/gi, 'estabilizado'],
  [/\btrigger\b/gi, 'desencadenar'],
  [/\btriggered\b/gi, 'desencadenado'],
  [/\bactivate\b/gi, 'activar'],
  [/\bactivated\b/gi, 'activado'],
  [/\bequip\b/gi, 'equipar'],
  [/\bwield\b/gi, 'empuñar'],
  [/\bwielding\b/gi, 'empuñando'],
  [/\bwields\b/gi, 'empuña'],
  [/\bholding\b/gi, 'sosteniendo'],
  [/\bholds?\b/gi, 'sostiene'],
  [/\bcarrying\b/gi, 'llevando'],
  [/\bcarries\b/gi, 'lleva'],
  [/\bcarry\b/gi, 'llevar'],
  [/\bwear\b/gi, 'llevar puesto'],
  [/\bwearing\b/gi, 'llevando puesto'],
  [/\bwears\b/gi, 'lleva puesto'],
  [/\bdraw\b/gi, 'desenfundar'],
  [/\bdrawing\b/gi, 'desenfundando'],
  [/\bdraws?\b/gi, 'desenfunda'],
  [/\bknock\b/gi, 'derribar'],
  [/\bpush\b/gi, 'empujar'],
  [/\bpull\b/gi, 'atraer'],
  [/\bmove\b/gi, 'mover'],
  [/\bmoves?\b/gi, 'mueve'],
  [/\bmoving\b/gi, 'moviéndose'],
  [/\bfly\b/gi, 'volar'],
  [/\bflies\b/gi, 'vuela'],
  [/\bflying\b/gi, 'volando'],
  [/\bswim\b/gi, 'nadar'],
  [/\bswims?\b/gi, 'nada'],
  [/\bswimming\b/gi, 'nadando'],
  [/\bclimb\b/gi, 'escalar'],
  [/\bclimbs?\b/gi, 'escala'],
  [/\bclimbing\b/gi, 'escalando'],
  [/\bcrawl\b/gi, 'arrastrarse'],
  [/\bstand\b/gi, 'ponerse en pie'],
  [/\bjump\b/gi, 'saltar'],

  // Common adjectives / descriptors
  [/\bmagically\b/gi, 'mágicamente'],
  [/\bmagical\b/gi, 'mágico'],
  [/\bnonmagical\b/gi, 'no mágico'],
  [/\bmagic\b/gi, 'mágico'],
  [/\binnately\b/gi, 'innátamente'],
  [/\binnate\b/gi, 'innato'],
  [/\bnatural\b/gi, 'natural'],
  [/\bphysical\b/gi, 'físico'],
  [/\bmental\b/gi, 'mental'],
  [/\bsupernatural\b/gi, 'sobrenatural'],
  [/\bautomatic\b/gi, 'automático'],
  [/\bautomatically\b/gi, 'automáticamente'],
  [/\bimmediate\b/gi, 'inmediato'],
  [/\bimmediately\b/gi, 'inmediatamente'],
  [/\bpermanent\b/gi, 'permanente'],
  [/\bpermanently\b/gi, 'permanentemente'],
  [/\btemporary\b/gi, 'temporal'],
  [/\btemporarily\b/gi, 'temporalmente'],
  [/\badditional\b/gi, 'adicional'],
  [/\bextra\b/gi, 'adicional'],
  [/\bspecial\b/gi, 'especial'],
  [/\bchoosen\b/gi, 'elegido'],
  [/\bchosen\b/gi, 'elegido'],
  [/\bspecified\b/gi, 'especificado'],
  [/\bindicated\b/gi, 'indicado'],
  [/\bvisible\b/gi, 'visible'],
  [/\binvisible\b/gi, 'invisible'],
  [/\bhidden\b/gi, 'oculto'],
  [/\bdeafened\b/gi, 'ensordecido'],
  [/\bblinded\b/gi, 'cegado'],
  [/\bfriendly\b/gi, 'amistoso'],
  [/\bhostile\b/gi, 'hostil'],
  [/\bneutral\b/gi, 'neutral'],
  [/\bwilling\b/gi, 'voluntario'],
  [/\bunwilling\b/gi, 'involuntario'],
  [/\badjacent\b/gi, 'adyacente'],
  [/\bnearby\b/gi, 'cercano'],
  [/\bunoccupied\b/gi, 'desocupado'],

  // Common nouns (generic)
  [/\bpoint\b/gi, 'punto'],
  [/\bpoints\b/gi, 'puntos'],
  [/\blevel\b/gi, 'nivel'],
  [/\blevels\b/gi, 'niveles'],
  [/\bturn\b/gi, 'turno'],
  [/\bturns\b/gi, 'turnos'],
  [/\brounds?\b/gi, 'ronda'],
  [/\bminutes?\b/gi, 'minuto'],
  [/\bhours?\b/gi, 'hora'],
  [/\bdays?\b/gi, 'día'],
  [/\bweeks?\b/gi, 'semana'],
  [/\byears?\b/gi, 'año'],
  [/\bfeet\b/gi, 'pies'],
  [/\bfoot\b/gi, 'pie'],
  [/\bmiles?\b/gi, 'milla'],
  [/\bdice\b/gi, 'dados'],
  [/\bdie\b/gi, 'dado'],
  [/\bpool\b/gi, 'reserva'],
  [/\bcharge\b/gi, 'carga'],
  [/\bcharges\b/gi, 'cargas'],
  [/\btotal\b/gi, 'total'],
  [/\bnumber\b/gi, 'número'],
  [/\bamount\b/gi, 'cantidad'],
  [/\bbonus\b/gi, 'bonificador'],
  [/\bpenalty\b/gi, 'penalización'],
  [/\bmodifier\b/gi, 'modificador'],
  [/\bsphere\b/gi, 'esfera'],
  [/\bcone\b/gi, 'cono'],
  [/\bcube\b/gi, 'cubo'],
  [/\bcylinder\b/gi, 'cilindro'],
  [/\bradius\b/gi, 'radio'],
  [/\brange\b/gi, 'alcance'],
  [/\bspeed\b/gi, 'velocidad'],
  [/\bweight\b/gi, 'peso'],
  [/\bcost\b/gi, 'coste'],
  [/\bprice\b/gi, 'precio'],
  [/\bgold\b/gi, 'oro'],
  [/\bsilver\b/gi, 'plata'],
  [/\bcopper\b/gi, 'cobre'],
  [/\bplatinum\b/gi, 'platino'],
  [/\bequipment\b/gi, 'equipo'],
  [/\bsupplies\b/gi, 'suministros'],
  [/\bsurface\b/gi, 'superficie'],
  [/\bground\b/gi, 'suelo'],
  [/\bfloor\b/gi, 'suelo'],
  [/\bwall\b/gi, 'pared'],
  [/\bceiling\b/gi, 'techo'],
  [/\bdoor\b/gi, 'puerta'],
  [/\bspace\b/gi, 'espacio'],
  [/\bsquare\b/gi, 'casilla'],
  [/\bcombat\b/gi, 'combate'],
  [/\bencounter\b/gi, 'encuentro'],
  [/\beffect\b/gi, 'efecto'],
  [/\beffects\b/gi, 'efectos'],
  [/\bfeature\b/gi, 'rasgo'],
  [/\bfeatures\b/gi, 'rasgos'],
  [/\bability\b/gi, 'habilidad'],
  [/\babilities\b/gi, 'habilidades'],
  [/\bpower\b/gi, 'poder'],
  [/\bpowers\b/gi, 'poderes'],
  [/\btrait\b/gi, 'rasgo'],
  [/\btraits\b/gi, 'rasgos'],
  [/\bclass\b/gi, 'clase'],
  [/\bsubclass\b/gi, 'subclase'],
  [/\brace\b/gi, 'raza'],
  [/\bbackground\b/gi, 'trasfondo'],
  [/\bfeat\b/gi, 'dote'],
  [/\bfeats\b/gi, 'dotes'],
  [/\btradition\b/gi, 'tradición'],
  [/\bpath\b/gi, 'senda'],
  [/\bschool\b/gi, 'escuela'],
  [/\border\b/gi, 'orden'],
  [/\boath\b/gi, 'juramento'],
  [/\bcircle\b/gi, 'círculo'],
  [/\bdomain\b/gi, 'dominio'],
  [/\barchetype\b/gi, 'arquetipo'],
  [/\bcollege\b/gi, 'colegio'],
  [/\bpatron\b/gi, 'patrón'],
  [/\borigin\b/gi, 'origen'],
  [/\blineage\b/gi, 'linaje'],
  [/\bblood\b/gi, 'sangre'],
  [/\bsoul\b/gi, 'alma'],
  [/\bsense\b/gi, 'sentido'],
  [/\bsenses\b/gi, 'sentidos'],
  [/\bvision\b/gi, 'visión'],
  [/\blight\b/gi, 'luz'],
  [/\bdarkness\b/gi, 'oscuridad'],
  [/\bshadow\b/gi, 'sombra'],
  [/\bflame\b/gi, 'llama'],
  [/\bice\b/gi, 'hielo'],
  [/\bwater\b/gi, 'agua'],
  [/\bearth\b/gi, 'tierra'],
  [/\bair\b/gi, 'aire'],
  [/\bwind\b/gi, 'viento'],
  [/\bstorm\b/gi, 'tormenta'],
  [/\bsky\b/gi, 'cielo'],
  [/\bsun\b/gi, 'sol'],
  [/\bmoon\b/gi, 'luna'],
  [/\bstar\b/gi, 'estrella'],
  [/\bstars\b/gi, 'estrellas'],
  [/\bplane\b/gi, 'plano'],
  [/\bplanes\b/gi, 'planos'],
  [/\bdimension\b/gi, 'dimensión'],
  [/\brealm\b/gi, 'reino'],
  [/\bworld\b/gi, 'mundo'],
  [/\bnature\b/gi, 'naturaleza'],
  [/\btime\b/gi, 'tiempo'],

  // Pronouns and articles in common contexts
  [/\bits\b/gi, 'su'],
  [/\btheir\b/gi, 'su'],
  [/\bthemselves\b/gi, 'ellos mismos'],
  [/\byourself\b/gi, 'ti mismo'],
  [/\bhimself\b/gi, 'él mismo'],
  [/\bherself\b/gi, 'ella misma'],
  [/\bitself\b/gi, 'sí mismo'],
  [/\boneself\b/gi, 'uno mismo'],
  [/\bwhich\b/gi, 'que'],
  [/\bwhere\b/gi, 'donde'],
  [/\bwhen\b/gi, 'cuando'],
  [/\bwhile\b/gi, 'mientras'],
  [/\buntil\b/gi, 'hasta que'],
  [/\bunless\b/gi, 'a menos que'],
  [/\bif\b/gi, 'si'],
  [/\botherwise\b/gi, 'de lo contrario'],
  [/\bhowever\b/gi, 'sin embargo'],
  [/\balso\b/gi, 'también'],
  [/\bonly\b/gi, 'solo'],
  [/\bjust\b/gi, 'solo'],
  [/\balready\b/gi, 'ya'],
  [/\bstill\b/gi, 'aún'],
  [/\bagain\b/gi, 'de nuevo'],
  [/\bonce\b/gi, 'una vez'],
  [/\btwice\b/gi, 'dos veces'],

  // Missing verbs
  [/\banimates?\b/gi, 'anima'],
  [/\banimated\b/gi, 'animado'],
  [/\banimating\b/gi, 'animando'],
  [/\bbecomes?\b/gi, 'se convierte en'],
  [/\bbecame\b/gi, 'se convirtió en'],
  [/\bbecome\b/gi, 'convertirse en'],
  [/\bcommands?\b/gi, 'ordena'],
  [/\bcommand\b/gi, 'ordenar'],
  [/\bcommanded\b/gi, 'ordenado'],
  [/\bcommanding\b/gi, 'ordenando'],
  [/\bcontrols?\b/gi, 'controla'],
  [/\bcontrol\b/gi, 'controlar'],
  [/\bcontrolled\b/gi, 'controlado'],
  [/\bcontrolling\b/gi, 'controlando'],
  [/\bfollows?\b/gi, 'sigue'],
  [/\bfollow\b/gi, 'seguir'],
  [/\bfollowed\b/gi, 'seguido'],
  [/\bfollowing\b/gi, 'siguiente'],
  [/\bcontinues?\b/gi, 'continúa'],
  [/\bcontinue\b/gi, 'continuar'],
  [/\bcontinued\b/gi, 'continuado'],
  [/\bstops?\b/gi, 'se detiene'],
  [/\bstopping\b/gi, 'deteniéndose'],
  [/\bstopped\b/gi, 'detenido'],
  [/\bstop\b/gi, 'detener'],
  [/\bobeying\b/gi, 'obedeciendo'],
  [/\bobeys?\b/gi, 'obedece'],
  [/\bobey\b/gi, 'obedecer'],
  [/\bobeyed\b/gi, 'obedecido'],
  [/\bmaintains?\b/gi, 'mantiene'],
  [/\bmaintain\b/gi, 'mantener'],
  [/\bmaintained\b/gi, 'mantenido'],
  [/\bmaintaining\b/gi, 'manteniendo'],
  [/\breasserts?\b/gi, 'reafirma'],
  [/\breassert\b/gi, 'reafirmar'],
  [/\breasserted\b/gi, 'reafirmado'],
  [/\bissues?\b/gi, 'da'],
  [/\bissuing\b/gi, 'dando'],
  [/\bissued\b/gi, 'dado'],
  [/\bguards?\b/gi, 'vigila'],
  [/\bguard\b/gi, 'vigilar'],
  [/\bguarded\b/gi, 'vigilado'],
  [/\bavoiding\b/gi, 'evitando'],
  [/\bavoided\b/gi, 'evitado'],
  [/\bavoids?\b/gi, 'evita'],
  [/\bavoid\b/gi, 'evitar'],
  [/\bsenses?\b/gi, 'percibe'],
  [/\bsensing\b/gi, 'percibiendo'],
  [/\bsensed\b/gi, 'percibido'],
  [/\bsense\b/gi, 'percibir'],
  [/\bknows?\b/gi, 'sabe'],
  [/\bknow\b/gi, 'saber'],
  [/\bknew\b/gi, 'supo'],
  [/\bknown\b/gi, 'sabido'],
  [/\bsees?\b/gi, 've'],
  [/\bseen\b/gi, 'visto'],
  [/\bsaw\b/gi, 'vio'],
  [/\blooks?\b/gi, 'mira'],
  [/\blooked\b/gi, 'mirado'],
  [/\blooking\b/gi, 'mirando'],
  [/\blook\b/gi, 'mirar'],
  [/\bhears?\b/gi, 'escucha'],
  [/\bheard\b/gi, 'escuchado'],
  [/\bhearing\b/gi, 'escuchando'],
  [/\bhear\b/gi, 'escuchar'],
  [/\bspeaks?\b/gi, 'habla'],
  [/\bspeak\b/gi, 'hablar'],
  [/\bspoke\b/gi, 'habló'],
  [/\bspoken\b/gi, 'hablado'],
  [/\btells?\b/gi, 'dice'],
  [/\btell\b/gi, 'decir'],
  [/\btold\b/gi, 'dijo'],
  [/\bsays?\b/gi, 'dice'],
  [/\bsaid\b/gi, 'dijo'],
  [/\bsay\b/gi, 'decir'],
  [/\bgives?\b/gi, 'da'],
  [/\bgive\b/gi, 'dar'],
  [/\bgiven\b/gi, 'dado'],
  [/\bgave\b/gi, 'dio'],
  [/\bgets?\b/gi, 'obtiene'],
  [/\bget\b/gi, 'obtener'],
  [/\bgot\b/gi, 'obtuvo'],
  [/\bgotten\b/gi, 'obtenido'],
  [/\bgetting\b/gi, 'obteniendo'],
  [/\buses?\b/gi, 'usa'],
  [/\busing\b/gi, 'usando'],
  [/\bused\b/gi, 'usado'],
  [/\buse\b/gi, 'usar'],
  [/\bneeds?\b/gi, 'necesita'],
  [/\bneed\b/gi, 'necesitar'],
  [/\bneeded\b/gi, 'necesitado'],
  [/\bneeding\b/gi, 'necesitando'],
  [/\bwants?\b/gi, 'quiere'],
  [/\bwant\b/gi, 'querer'],
  [/\bwanted\b/gi, 'querido'],
  [/\btries?\b/gi, 'intenta'],
  [/\btry\b/gi, 'intentar'],
  [/\btried\b/gi, 'intentado'],
  [/\btrying\b/gi, 'intentando'],
  [/\battempts?\b/gi, 'intenta'],
  [/\battempt\b/gi, 'intentar'],
  [/\battempted\b/gi, 'intentado'],
  [/\battempting\b/gi, 'intentando'],
  [/\bdelivers?\b/gi, 'entrega'],
  [/\bdeliver\b/gi, 'entregar'],
  [/\bdelivered\b/gi, 'entregado'],
  [/\bdelivering\b/gi, 'entregando'],
  [/\bdescribes?\b/gi, 'describe'],
  [/\bdescribe\b/gi, 'describir'],
  [/\bdescribed\b/gi, 'descrito'],
  [/\bspecifies?\b/gi, 'especifica'],
  [/\bspecify\b/gi, 'especificar'],
  [/\bspecified\b/gi, 'especificado'],
  [/\bmatches?\b/gi, 'coincide con'],
  [/\bmatch\b/gi, 'coincidir con'],
  [/\bmatched\b/gi, 'coincidido'],
  [/\bincludes?\b/gi, 'incluye'],
  [/\binclude\b/gi, 'incluir'],
  [/\bincluded\b/gi, 'incluido'],
  [/\ballows?\b/gi, 'permite'],
  [/\ballow\b/gi, 'permitir'],
  [/\ballowed\b/gi, 'permitido'],
  [/\brequires?\b/gi, 'requiere'],
  [/\brequire\b/gi, 'requerir'],
  [/\brequired\b/gi, 'requerido'],
  [/\bprovides?\b/gi, 'proporciona'],
  [/\bprovide\b/gi, 'proporcionar'],
  [/\bprovided\b/gi, 'proporcionado'],
  [/\bcontains?\b/gi, 'contiene'],
  [/\bcontain\b/gi, 'contener'],
  [/\bcontained\b/gi, 'contenido'],
  [/\brepresents?\b/gi, 'representa'],
  [/\brepresent\b/gi, 'representar'],
  [/\brepresented\b/gi, 'representado'],
  [/\bdetermines?\b/gi, 'determina'],
  [/\bdetermine\b/gi, 'determinar'],
  [/\bdetermined\b/gi, 'determinado'],
  [/\bsuffers?\b/gi, 'sufre'],
  [/\bsuffer\b/gi, 'sufrir'],
  [/\bsuffered\b/gi, 'sufrido'],
  [/\bsuffering\b/gi, 'sufriendo'],
  [/\bwithstands?\b/gi, 'resiste'],
  [/\bwithstand\b/gi, 'resistir'],
  [/\bwithstood\b/gi, 'resistido'],
  [/\bperforms?\b/gi, 'realiza'],
  [/\bperform\b/gi, 'realizar'],
  [/\bperformed\b/gi, 'realizado'],
  [/\bperforming\b/gi, 'realizando'],
  [/\bnotes?\b/gi, 'anota'],
  [/\bnote\b/gi, 'anotar'],
  [/\breaches?\b/gi, 'llega a'],
  [/\breach\b/gi, 'llegar a'],
  [/\breached\b/gi, 'llegado a'],

  // Missing nouns
  [/\bbones?\b/gi, 'hueso'],
  [/\bcorpses?\b/gi, 'cadáver'],
  [/\bskeletons?\b/gi, 'esqueleto'],
  [/\bzombies?\b/gi, 'zombi'],
  [/\bpile\b/gi, 'montón'],
  [/\btask\b/gi, 'tarea'],
  [/\btasks\b/gi, 'tareas'],
  [/\bchambers?\b/gi, 'cámara'],
  [/\bcorridors?\b/gi, 'corredor'],
  [/\bharm\b/gi, 'daño'],
  [/\bcommand\b/gi, 'orden'],
  [/\bcommands\b/gi, 'órdenes'],
  [/\border\b/gi, 'orden'],
  [/\borders\b/gi, 'órdenes'],
  [/\bcontrol\b/gi, 'control'],
  [/\bperiod\b/gi, 'período'],
  [/\bperiods\b/gi, 'períodos'],
  [/\brecipient\b/gi, 'destinatario'],
  [/\bdescription\b/gi, 'descripción'],
  [/\bperson\b/gi, 'persona'],
  [/\bpersons\b/gi, 'personas'],
  [/\buniform\b/gi, 'uniforme'],
  [/\btown\b/gi, 'ciudad'],
  [/\bguard\b/gi, 'guardia'],
  [/\bguards\b/gi, 'guardias'],
  [/\bskin\b/gi, 'piel'],
  [/\bhair\b/gi, 'cabello'],
  [/\beyes\b/gi, 'ojos'],
  [/\bwords\b/gi, 'palabras'],
  [/\bword\b/gi, 'palabra'],
  [/\bmessage\b/gi, 'mensaje'],
  [/\bmessages\b/gi, 'mensajes'],
  [/\bdestination\b/gi, 'destino'],
  [/\bsource\b/gi, 'fuente'],
  [/\btravel\b/gi, 'viajar'],
  [/\btravels\b/gi, 'viaja'],
  [/\btraveling\b/gi, 'viajando'],
  [/\btraveled\b/gi, 'viajado'],
  [/\bcovering\b/gi, 'cubriendo'],
  [/\bcovers?\b/gi, 'cubre'],
  [/\bcover\b/gi, 'cubrir'],

  // Missing adjectives / adverbs
  [/\bmentally\b/gi, 'mentalmente'],
  [/\bmultiple\b/gi, 'múltiples'],
  [/\bgeneral\b/gi, 'general'],
  [/\bcurrent\b/gi, 'actual'],
  [/\bnew\b/gi, 'nuevo'],
  [/\bnext\b/gi, 'siguiente'],
  [/\bsame\b/gi, 'mismo'],
  [/\bdifferent\b/gi, 'diferente'],
  [/\bother\b/gi, 'otro'],
  [/\banother\b/gi, 'otro'],
  [/\bfour\b/gi, 'cuatro'],
  [/\bfive\b/gi, 'cinco'],
  [/\bsix\b/gi, 'seis'],
  [/\bseven\b/gi, 'siete'],
  [/\beight\b/gi, 'ocho'],
  [/\bnine\b/gi, 'nueve'],
  [/\bten\b/gi, 'diez'],
  [/\btwenty\b/gi, 'veinte'],
  [/\btwenty-five\b/gi, 'veinticinco'],
  [/\bthirty\b/gi, 'treinta'],
  [/\bforty\b/gi, 'cuarenta'],
  [/\bfifty\b/gi, 'cincuenta'],
  [/\bhundred\b/gi, 'cien'],
  [/\bfirst\b/gi, 'primero'],
  [/\bsecond\b/gi, 'segundo'],
  [/\bthird\b/gi, 'tercero'],
  [/\bfourth\b/gi, 'cuarto'],
  [/\bfifth\b/gi, 'quinto'],
  [/\bninth\b/gi, 'noveno'],
  [/\bany\b/gi, 'cualquier'],
  [/\beach\b/gi, 'cada'],
  [/\bevery\b/gi, 'todo'],
  [/\beveryone\b/gi, 'todos'],
  [/\beverything\b/gi, 'todo'],
  [/\bsome\b/gi, 'algún'],
  [/\bseveral\b/gi, 'varios'],
  [/\bmany\b/gi, 'muchos'],
  [/\bfew\b/gi, 'pocos'],
  [/\bmuch\b/gi, 'mucho'],
  [/\blittle\b/gi, 'poco'],
  [/\ball\b/gi, 'todo'],
  [/\bnone\b/gi, 'ninguno'],
  [/\bno\b/gi, 'ningún'],
  [/\bnot\b/gi, 'no'],
  [/\bnor\b/gi, 'ni'],
  [/\band\b/gi, 'y'],
  [/\bor\b/gi, 'o'],
  [/\bbut\b/gi, 'pero'],
  [/\bso\b/gi, 'así que'],
  [/\byet\b/gi, 'sin embargo'],
  [/\bboth\b/gi, 'ambos'],
  [/\beither\b/gi, 'cualquiera de los dos'],
  [/\bneither\b/gi, 'ninguno de los dos'],
  [/\bmore\b/gi, 'más'],
  [/\bmost\b/gi, 'la mayoría'],
  [/\bless\b/gi, 'menos'],
  [/\bleast\b/gi, 'el menor'],
  [/\bvery\b/gi, 'muy'],
  [/\bquite\b/gi, 'bastante'],
  [/\brather\b/gi, 'bastante'],
  [/\btoo\b/gi, 'también'],
  [/\beven\b/gi, 'incluso'],
  [/\bnever\b/gi, 'nunca'],
  [/\balways\b/gi, 'siempre'],
  [/\boften\b/gi, 'a menudo'],
  [/\bsometimes\b/gi, 'a veces'],
  [/\busually\b/gi, 'normalmente'],
  [/\bgenerally\b/gi, 'generalmente'],
  [/\bspecifically\b/gi, 'específicamente'],
  [/\bparticularly\b/gi, 'particularmente'],
  [/\bespecially\b/gi, 'especialmente'],
  [/\btherefore\b/gi, 'por lo tanto'],
  [/\balthough\b/gi, 'aunque'],
  [/\bthough\b/gi, 'aunque'],
  [/\bnow\b/gi, 'ahora'],
  [/\bthen\b/gi, 'entonces'],
  [/\bhere\b/gi, 'aquí'],
  [/\bthere\b/gi, 'allí'],
  [/\blong\b/gi, 'largo'],
  [/\bshort\b/gi, 'corto'],
  [/\bhigh\b/gi, 'alto'],
  [/\blow\b/gi, 'bajo'],
  [/\blarge\b/gi, 'grande'],
  [/\bsmall\b/gi, 'pequeño'],
  [/\bbig\b/gi, 'grande'],
  [/\bold\b/gi, 'viejo'],
  [/\bgood\b/gi, 'bueno'],
  [/\bbad\b/gi, 'malo'],
  [/\bgreat\b/gi, 'excelente'],
  [/\bimportant\b/gi, 'importante'],
  [/\bpossible\b/gi, 'posible'],
  [/\bimpossible\b/gi, 'imposible'],
  [/\bnecessary\b/gi, 'necesario'],
  [/\bavailable\b/gi, 'disponible'],
  [/\bcommon\b/gi, 'común'],
  [/\bmain\b/gi, 'principal'],
  [/\bmajor\b/gi, 'mayor'],
  [/\bminor\b/gi, 'menor'],
  [/\bdirect\b/gi, 'directo'],
  [/\bindirect\b/gi, 'indirecto'],
  [/\bnormal\b/gi, 'normal'],
  [/\bstandard\b/gi, 'estándar'],
  [/\bbasic\b/gi, 'básico'],
  [/\bsimple\b/gi, 'simple'],
  [/\bcomplex\b/gi, 'complejo'],
  [/\bfull\b/gi, 'completo'],
  [/\bhalf\b/gi, 'la mitad'],
  [/\bquarter\b/gi, 'un cuarto'],
  [/\bdouble\b/gi, 'el doble'],
  [/\bsingle\b/gi, 'único'],
  [/\bseveral\b/gi, 'varios'],
  [/\bmedium\b/gi, 'mediana'],
  [/\bdressed\b/gi, 'vestida'],
  [/\bpointed\b/gi, 'puntiagudo'],
  [/\bred-haired\b/gi, 'pelirrojo'],
  [/\bwearing\b/gi, 'llevando'],
  [/\bhalf\b/gi, 'la mitad'],
  [/\bhat\b/gi, 'sombrero'],

  // Prepositions (generic fallback — after specific phrases)
  [/\bwithin\b/gi, 'dentro de'],
  [/\bwithout\b/gi, 'sin'],
  [/\bbeyond\b/gi, 'más allá de'],
  [/\bagainst\b/gi, 'contra'],
  [/\bthrough\b/gi, 'a través de'],
  [/\balong\b/gi, 'a lo largo de'],
  [/\baround\b/gi, 'alrededor de'],
  [/\babove\b/gi, 'por encima de'],
  [/\bbelow\b/gi, 'por debajo de'],
  [/\bnear\b/gi, 'cerca de'],
  [/\bbehind\b/gi, 'detrás de'],
  [/\bbeside\b/gi, 'junto a'],
  [/\bbetween\b/gi, 'entre'],
  [/\bamong\b/gi, 'entre'],
  [/\btoward\b/gi, 'hacia'],
  [/\btowards\b/gi, 'hacia'],
  [/\bonto\b/gi, 'sobre'],
  [/\binto\b/gi, 'dentro de'],
  [/\bover\b/gi, 'sobre'],
  [/\bunder\b/gi, 'bajo'],
  [/\bbefore\b/gi, 'antes de'],
  [/\bafter\b/gi, 'después de'],
  [/\bduring\b/gi, 'durante'],
  [/\bsince\b/gi, 'desde'],
  [/\bfrom\b/gi, 'desde'],
  [/\bwith\b/gi, 'con'],
  [/\bby\b/gi, 'por'],
  [/\bfor\b/gi, 'para'],
  [/\bof\b/gi, 'de'],
  [/\bin\b/gi, 'en'],
  [/\bon\b/gi, 'en'],
  [/\bat\b/gi, 'a'],
  [/\bto\b/gi, 'a'],

  // Articles (last resort fallback)
  // Demonstratives (specific before generic)
  [/\bthis spell\b/gi, 'este conjuro'],
  [/\bthis feature\b/gi, 'este rasgo'],
  [/\bthis ability\b/gi, 'esta habilidad'],
  [/\bthis effect\b/gi, 'este efecto'],
  [/\bthis damage\b/gi, 'este daño'],
  [/\bthis attack\b/gi, 'este ataque'],
  [/\bthis turn\b/gi, 'este turno'],
  [/\bthis way\b/gi, 'de este modo'],
  [/\bthis manner\b/gi, 'de esta manera'],
  [/\bthis action\b/gi, 'esta acción'],
  [/\bthis save\b/gi, 'esta salvación'],
  [/\bthis saving throw\b/gi, 'esta tirada de salvación'],
  [/\bthese spells\b/gi, 'estos conjuros'],
  [/\bthese creatures\b/gi, 'estas criaturas'],
  [/\bthese effects\b/gi, 'estos efectos'],
  [/\bthat creature\b/gi, 'esa criatura'],
  [/\bthat attack\b/gi, 'ese ataque'],
  [/\bthat damage\b/gi, 'ese daño'],
  [/\bthat spell\b/gi, 'ese conjuro'],
  [/\bthat effect\b/gi, 'ese efecto'],
  [/\bthat target\b/gi, 'ese objetivo'],
  // "that" as relative pronoun (most common D&D usage)
  [/\bthat\b/gi, 'que'],
  [/\bthis\b/gi, 'este'],
  [/\bthese\b/gi, 'estos'],
  [/\bthose\b/gi, 'esos'],
  [/\bsuch\b/gi, 'tal'],

  // Numbers (one/two/three are common; must come after specific "one creature" etc. phrases above)
  [/\bone\b/gi, 'un'],
  [/\btwo\b/gi, 'dos'],
  [/\bthree\b/gi, 'tres'],

  // Last-resort article fallbacks (after all specific patterns exhausted)
  [/\ban\b/gi, 'un'],
  [/\bthe\b/gi, 'el'],
]

export function translateText(text) {
  if (typeof text !== 'string') return text
  let result = text
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement)
  }
  return result
}
