// Official Spanish D&D spell names (Edge/Wizards ES)
export const SPELL_NAMES_ES = {
  'Acid Splash': 'Salpicadura de Ácido',
  'Aid': 'Ayuda',
  'Alarm': 'Alarma',
  'Alter Self': 'Alterarse',
  'Animal Friendship': 'Amistad con los Animales',
  'Animal Messenger': 'Mensajero Animal',
  'Animate Dead': 'Animar Muertos',
  'Animate Objects': 'Animar Objetos',
  'Antilife Shell': 'Escudo Antinatural',
  'Antipathy/Sympathy': 'Antipatía/Simpatía',
  'Arcane Eye': 'Ojo Arcano',
  'Arcane Gate': 'Portal Arcano',
  'Arcane Lock': 'Cerradura Arcana',
  'Arcane Vigor': 'Vigor Arcano',
  'Armor of Agathys': 'Armadura de Agatias',
  'Arms of Hadar': 'Brazos de Hadar',
  'Astral Projection': 'Proyección Astral',
  'Augury': 'Augurio',
  'Aura of Life': 'Aura de Vida',
  'Aura of Purity': 'Aura de Pureza',
  'Aura of Vitality': 'Aura de Vitalidad',
  'Awaken': 'Despertar',
  'Bane': 'Perdición',
  'Banishment': 'Destierro',
  'Barkskin': 'Corteza Arbórea',
  'Beacon of Hope': 'Baliza de Esperanza',
  'Bestow Curse': 'Maldición',
  "Bigby's Hand": 'Mano de Bigby',
  'Blade Barrier': 'Barrera de Cuchillas',
  'Blade Ward': 'Escudo de Cuchillas',
  'Bless': 'Bendición',
  'Blight': 'Plaga',
  'Blindness/Deafness': 'Ceguera/Sordera',
  'Blink': 'Parpadeo',
  'Blur': 'Borrosidad',
  'Burning Hands': 'Manos Ardientes',
  'Call Lightning': 'Llamar Relámpago',
  'Calm Emotions': 'Calmar Emociones',
  'Chain Lightning': 'Relámpago en Cadena',
  'Charm Monster': 'Encantar Monstruo',
  'Charm Person': 'Encantar Persona',
  'Chill Touch': 'Toque Gélido',
  'Circle of Death': 'Círculo de la Muerte',
  'Clairvoyance': 'Clarividencia',
  'Clone': 'Clonar',
  'Cloud of Daggers': 'Nube de Dagas',
  'Cloudkill': 'Nube Asesina',
  'Color Spray': 'Spray de Colores',
  'Command': 'Orden',
  'Commune': 'Comunión',
  'Commune with Nature': 'Comunión con la Naturaleza',
  'Comprehend Languages': 'Comprender Idiomas',
  'Compulsion': 'Compulsión',
  'Cone of Cold': 'Cono de Frío',
  'Confusion': 'Confusión',
  'Conjure Animals': 'Convocar Animales',
  'Conjure Barrage': 'Convocar Barrera',
  'Conjure Celestial': 'Convocar Celestial',
  'Conjure Elemental': 'Convocar Elemental',
  'Conjure Fey': 'Convocar Feérico',
  'Conjure Minor Elementals': 'Convocar Elementales Menores',
  'Conjure Volley': 'Convocar Lluvia',
  'Conjure Woodland Beings': 'Convocar Seres del Bosque',
  'Contact Other Plane': 'Contactar otro Plano',
  'Contagion': 'Contagio',
  'Contingency': 'Contingencia',
  'Continual Flame': 'Llama Continua',
  'Control Water': 'Controlar el Agua',
  'Control Weather': 'Controlar el Clima',
  'Cordon of Arrows': 'Cordón de Flechas',
  'Counterspell': 'Contraconjuro',
  'Create Food and Water': 'Crear Comida y Agua',
  'Create or Destroy Water': 'Crear o Destruir Agua',
  'Create Undead': 'Crear No Muertos',
  'Cure Wounds': 'Curar Heridas',
  'Dancing Lights': 'Luces Danzantes',
  'Darkness': 'Oscuridad',
  'Darkvision': 'Visión en la Oscuridad',
  'Daylight': 'Luz del Día',
  'Death Ward': 'Escudo contra la Muerte',
  'Delayed Blast Fireball': 'Bola de Fuego de Explosión Retardada',
  'Detect Evil and Good': 'Detectar el Bien y el Mal',
  'Detect Magic': 'Detectar Magia',
  'Detect Poison and Disease': 'Detectar Veneno y Enfermedad',
  'Detect Thoughts': 'Detectar Pensamientos',
  'Dimension Door': 'Puerta Dimensional',
  'Disguise Self': 'Disfrazarse',
  'Disintegrate': 'Desintegrar',
  'Dispel Evil and Good': 'Disipar el Bien y el Mal',
  'Dispel Magic': 'Disipar Magia',
  'Divination': 'Adivinación',
  'Divine Favor': 'Favor Divino',
  'Divine Smite': 'Castigo Divino',
  'Divine Word': 'Palabra Divina',
  'Dominate Beast': 'Dominar Bestia',
  'Dominate Monster': 'Dominar Monstruo',
  'Dominate Person': 'Dominar Persona',
  'Dream': 'Sueño',
  'Druidcraft': 'Druidestreza',
  'Earthquake': 'Terremoto',
  'Eldritch Blast': 'Explosión Sobrenatural',
  'Elemental Weapon': 'Arma Elemental',
  'Enhance Ability': 'Mejorar Habilidad',
  'Enlarge/Reduce': 'Agrandar/Reducir',
  'Entangle': 'Enredar',
  'Enthrall': 'Encandilar',
  'Etherealness': 'Etereidad',
  'Expeditious Retreat': 'Retirada Expeditiva',
  'Eyebite': 'Mirada Venenosa',
  'Fabricate': 'Fabricar',
  'Faerie Fire': 'Fuego de las Hadas',
  "Faithful Hound": 'Mastín Leal',
  'False Life': 'Vida Falsa',
  'Fear': 'Miedo',
  'Feather Fall': 'Caída de Pluma',
  'Feeblemind': 'Debilitar Mente',
  'Find Familiar': 'Encontrar Familiar',
  'Find the Path': 'Encontrar el Camino',
  'Find Traps': 'Encontrar Trampas',
  'Fire Bolt': 'Rayo de Fuego',
  'Fire Shield': 'Escudo de Fuego',
  'Fire Storm': 'Tormenta de Fuego',
  'Fireball': 'Bola de Fuego',
  'Flame Blade': 'Hoja de Llamas',
  'Flame Strike': 'Golpe de Llama',
  'Flaming Sphere': 'Esfera en Llamas',
  'Flesh to Stone': 'Carne a Piedra',
  'Fly': 'Volar',
  'Fog Cloud': 'Nube de Niebla',
  'Forbiddance': 'Prohibición',
  'Forcecage': 'Jaula de Fuerza',
  'Foresight': 'Presciencia',
  'Freedom of Movement': 'Libertad de Movimiento',
  'Friends': 'Amigos',
  'Gaseous Form': 'Forma Gaseosa',
  'Gate': 'Portal',
  'Geas': 'Geas',
  'Gentle Repose': 'Reposo Plácido',
  'Giant Insect': 'Insecto Gigante',
  'Glibness': 'Labia',
  'Globe of Invulnerability': 'Globo de Invulnerabilidad',
  'Glyph of Warding': 'Glifo de Guardia',
  'Goodberry': 'Baya Bondadosa',
  'Grease': 'Grasa',
  'Greater Invisibility': 'Invisibilidad Superior',
  'Greater Restoration': 'Restauración Superior',
  'Guardian of Faith': 'Guardián de la Fe',
  'Guards and Wards': 'Guardas y Vigilantes',
  'Guidance': 'Guía',
  'Guiding Bolt': 'Rayo Guía',
  'Gust of Wind': 'Ráfaga de Viento',
  'Hallow': 'Consagrar',
  'Hallucinatory Terrain': 'Terreno Alucinatorio',
  'Harm': 'Dañar',
  'Haste': 'Apresuramiento',
  'Heal': 'Curar',
  'Healing Word': 'Palabra Curativa',
  'Heat Metal': 'Metal Candente',
  'Hellish Rebuke': 'Represalia Infernal',
  "Heroes' Feast": 'Festín de los Héroes',
  'Heroism': 'Heroísmo',
  'Hold Monster': 'Paralizar Monstruo',
  'Hold Person': 'Paralizar Persona',
  'Holy Aura': 'Aura Sagrada',
  'Hunger of Hadar': 'Hambre de Hadar',
  "Hunter's Mark": 'Marca del Cazador',
  'Hypnotic Pattern': 'Patrón Hipnótico',
  'Ice Storm': 'Tormenta de Hielo',
  'Identify': 'Identificar',
  'Illusory Script': 'Escritura Ilusoria',
  'Imprisonment': 'Encarcelamiento',
  'Incendiary Cloud': 'Nube Incendiaria',
  'Inflict Wounds': 'Infligir Heridas',
  'Insect Plague': 'Plaga de Insectos',
  'Instant Summons': 'Convocación Instantánea',
  'Invisibility': 'Invisibilidad',
  'Jump': 'Saltar',
  'Knock': 'Abrir',
  'Legend Lore': 'Leyendas',
  "Leomund's Secret Chest": 'Arcón Secreto de Leomund',
  "Leomund's Tiny Hut": 'Cabaña Diminuta de Leomund',
  'Lesser Restoration': 'Restauración Menor',
  'Levitate': 'Levitar',
  'Light': 'Luz',
  'Lightning Arrow': 'Flecha de Relámpago',
  'Lightning Bolt': 'Rayo',
  'Locate Animals or Plants': 'Localizar Animales o Plantas',
  'Locate Creature': 'Localizar Criatura',
  'Locate Object': 'Localizar Objeto',
  'Longstrider': 'Paso Largo',
  'Mage Armor': 'Armadura del Mago',
  'Mage Hand': 'Mano del Mago',
  'Magic Circle': 'Círculo Mágico',
  'Magic Jar': 'Frasco Mágico',
  'Magic Missile': 'Proyectil Mágico',
  'Magic Mouth': 'Boca Mágica',
  'Magic Weapon': 'Arma Mágica',
  'Major Image': 'Imagen Mayor',
  'Mass Cure Wounds': 'Curar Heridas Masivo',
  'Mass Heal': 'Curación Masiva',
  'Mass Healing Word': 'Palabra Curativa Masiva',
  'Mass Polymorph': 'Polimorfia Masiva',
  'Mass Suggestion': 'Sugestión Masiva',
  'Maze': 'Laberinto',
  'Meld into Stone': 'Fundirse con la Piedra',
  'Mending': 'Reparar',
  'Message': 'Mensaje',
  'Meteor Swarm': 'Lluvia de Meteoros',
  'Mind Blank': 'Mente en Blanco',
  'Minor Illusion': 'Ilusión Menor',
  'Mirage Arcane': 'Espejismo Arcano',
  'Mirror Image': 'Imagen Especular',
  'Mislead': 'Extraviar',
  'Misty Step': 'Paso Neblinoso',
  'Modify Memory': 'Modificar Memoria',
  'Moonbeam': 'Rayo de Luna',
  'Move Earth': 'Mover la Tierra',
  'Nondetection': 'No Detección',
  "Nystul's Magic Aura": 'Aura Mágica de Nystul',
  "Otto's Irresistible Dance": 'Danza Irresistible de Otto',
  'Pass without Trace': 'Pasar sin Dejar Rastro',
  'Passwall': 'Paso por Muros',
  'Phantasmal Force': 'Fuerza Fantasmal',
  'Phantasmal Killer': 'Asesino Fantasmal',
  'Phantom Steed': 'Corcel Fantasma',
  'Planar Ally': 'Aliado Planar',
  'Planar Binding': 'Vinculación Planar',
  'Plane Shift': 'Cambio de Plano',
  'Plant Growth': 'Crecimiento Vegetal',
  'Poison Spray': 'Nube de Veneno',
  'Polymorph': 'Polimorfia',
  'Power Word Fortify': 'Palabra de Poder: Fortalecer',
  'Power Word Heal': 'Palabra de Poder: Curar',
  'Power Word Kill': 'Palabra de Poder: Matar',
  'Power Word Stun': 'Palabra de Poder: Aturdir',
  'Prayer of Healing': 'Oración Curativa',
  'Prestidigitation': 'Prestidigitación',
  'Prismatic Spray': 'Spray Prismático',
  'Prismatic Wall': 'Muro Prismático',
  'Produce Flame': 'Producir Llama',
  'Protection from Energy': 'Protección contra la Energía',
  'Protection from Evil and Good': 'Protección contra el Bien y el Mal',
  'Protection from Poison': 'Protección contra el Veneno',
  'Purify Food and Drink': 'Purificar Alimentos y Bebidas',
  'Raise Dead': 'Resucitar Muertos',
  'Ray of Enfeeblement': 'Rayo de Debilitamiento',
  'Ray of Frost': 'Rayo de Escarcha',
  'Ray of Sickness': 'Rayo de Enfermedad',
  'Regenerate': 'Regenerar',
  'Reincarnate': 'Reencarnar',
  'Remove Curse': 'Eliminar Maldición',
  'Resistance': 'Resistencia',
  'Resurrection': 'Resurrección',
  'Reverse Gravity': 'Invertir Gravedad',
  'Revivify': 'Revivir',
  'Sacred Flame': 'Llama Sagrada',
  'Sanctuary': 'Santuario',
  'Scorching Ray': 'Rayo Abrasador',
  'Seeming': 'Apariencia',
  'Sending': 'Enviar',
  'Sequester': 'Secuestrar',
  'Shapechange': 'Transformar',
  'Shatter': 'Estallido',
  'Shield': 'Escudo',
  'Shield of Faith': 'Escudo de Fe',
  'Shillelagh': 'Shillelagh',
  'Shocking Grasp': 'Agarre Eléctrico',
  'Silence': 'Silencio',
  'Silent Image': 'Imagen Silenciosa',
  'Simulacrum': 'Simulacro',
  'Sleep': 'Dormir',
  'Sleet Storm': 'Tormenta de Aguanieve',
  'Slow': 'Ralentizar',
  'Spare the Dying': 'Salvar al Moribundo',
  'Speak with Animals': 'Hablar con Animales',
  'Speak with Dead': 'Hablar con los Muertos',
  'Speak with Plants': 'Hablar con las Plantas',
  'Spider Climb': 'Trepar como Araña',
  'Spike Growth': 'Crecimiento de Pinchos',
  'Spirit Guardians': 'Guardianes Espirituales',
  'Spirit of Death': 'Espíritu de la Muerte',
  'Spiritual Weapon': 'Arma Espiritual',
  'Staggering Smite': 'Golpe Tambaleante',
  'Stone Shape': 'Dar Forma a la Piedra',
  'Stoneskin': 'Piel Pétrea',
  'Storm of Vengeance': 'Tormenta de Venganza',
  'Suggestion': 'Sugestión',
  'Sunbeam': 'Rayo de Sol',
  'Sunburst': 'Explosión Solar',
  'Symbol': 'Símbolo',
  'Synaptic Static': 'Estática Sináptica',
  "Tasha's Hideous Laughter": 'Risa Horrenda de Tasha',
  'Telekinesis': 'Telequinesis',
  'Telepathy': 'Telepatía',
  'Teleport': 'Teleporte',
  'Teleportation Circle': 'Círculo de Teleportación',
  'Thaumaturgy': 'Taumaturgia',
  'Thorn Whip': 'Látigo de Espinas',
  'Thunderclap': 'Truenazo',
  'Thunderous Smite': 'Golpe Atronador',
  'Thunderwave': 'Onda de Trueno',
  'Time Stop': 'Detener el Tiempo',
  'Toll the Dead': 'Doblar las Campanas',
  'Tongues': 'Lenguas',
  'Transport via Plants': 'Transporte Vegetal',
  'Tree Stride': 'Paso Arbóreo',
  'True Polymorph': 'Polimorfia Verdadera',
  'True Resurrection': 'Resurrección Verdadera',
  'True Seeing': 'Visión Verdadera',
  'True Strike': 'Golpe Certero',
  'Tsunami': 'Tsunami',
  'Unseen Servant': 'Sirviente Invisible',
  'Vampiric Touch': 'Toque Vampírico',
  'Vicious Mockery': 'Burla Viciosa',
  'Wall of Fire': 'Muro de Fuego',
  'Wall of Force': 'Muro de Fuerza',
  'Wall of Ice': 'Muro de Hielo',
  'Wall of Stone': 'Muro de Piedra',
  'Wall of Thorns': 'Muro de Espinas',
  'Warding Bond': 'Vínculo Protector',
  'Water Breathing': 'Respirar bajo el Agua',
  'Water Walk': 'Caminar sobre el Agua',
  'Web': 'Telaraña',
  'Wind Walk': 'Caminar con el Viento',
  'Wind Wall': 'Muro de Viento',
  'Wish': 'Deseo',
  'Witch Bolt': 'Rayo de Bruja',
  'Word of Radiance': 'Palabra de Resplandor',
  'Word of Recall': 'Palabra de Regreso',
  'Wrathful Smite': 'Golpe Iracundo',
  'Zone of Truth': 'Zona de la Verdad',
}

export function translateSpellName(name) {
  return SPELL_NAMES_ES[name] ?? name
}
